f=open("abc.txt","w")
print("initial",f.tell())
f.seek(81)
f.write("\nVISHNU INSTITUTE OF TECHNOLOGY")
#print(f.tell())
f.seek(0)
f.writelines(" ython is a high-level, general-purpose programming.\n")
#f.seek(31)
f.write("VISHNU EDUCATIONAL SOCIETY")
print(f.tell())
f.seek(0)
f.write("P")
f=open("abc.txt","r")
print(f.read())
print(f.tell())
f.close()
print("SUCCESSFUL")